CREATE DATABASE IF NOT EXISTS `hero`;

USE hero;

CREATE TABLE IF NOT EXISTS users (
  id INT NOT NULL AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL,
  logins INT NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
);
